# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='session',
            field=models.IntegerField(),
        ),
    ]
