# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('meals', models.CharField(max_length=30)),
                ('billing_firstname', models.CharField(max_length=30)),
                ('billing_lastname', models.CharField(max_length=30)),
                ('card_type', models.CharField(max_length=15)),
                ('card_number', models.CharField(max_length=30)),
                ('card_csv', models.CharField(max_length=4)),
                ('exp_year', models.CharField(max_length=4)),
                ('exp_month', models.CharField(max_length=2)),
                ('session1', models.CharField(max_length=30)),
                ('session2', models.CharField(max_length=30)),
                ('session3', models.CharField(max_length=30)),
            ],
        ),
    ]
